server:
  port: 10000
  servlet:
    context-path: /faketube-service           
           
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:1000/auth/user
    client:
      client-id: faketube
      client-secret: faketube-super-secure
#      access-token-uri: http://localhost:1000/user
#      user-authorization-uri: 

spring:
  application:
    name: faketube-service